// src/pages/Home.tsx
import React from "react";
import { Banner } from "../components/Banner";
import { Featured } from "../components/Featured"
import { Sponsors } from "../components/Sponsors";
import { Volunteer } from "../components/Volunteer";

export function Home() {
  return (
    <>
      <Banner/>
      <Volunteer />
      <Featured />
      <Sponsors />
    </>
  );
}

// src/views/Home.vue
<template>
  <div class="home">
    <Banner/>
    <WhatWeDo/>
    <ExploreProjects/>
    <Info/>
    <OurSponsors/>
  </div>
</template>

<script>
import Banner from '@/components/home/Banner.vue'
import ExploreProjects from '@/components/home/ExploreProjects.vue'
import Info from '@/components/home/Info.vue'
import OurSponsors from '@/components/home/OurSponsors.vue'
import ProjectCards from '@/components/home/ProjectCards.vue'
import WhatWeDo from '@/components/home/WhatWeDo.vue'

export default {
  name: 'home',
  components: {
    Banner,
    ExploreProjects,
    Info,
    OurSponsors,
    ProjectCards,
    WhatWeDo
  }
}
</script>
